+incdir+../../submodules/PulseRain_MCU/common/
+incdir+../../submodules/PulseRain_MCU/memory/microsemi
+incdir+../../submodules/PulseRain_MCU/common/Microsemi/SmartFusion2
+incdir+../../submodules/PulseRain_MCU/PulseRain_processor_core/source
+incdir+../../submodules/PulseRain_MCU/PulseRain_processor_core/source/mul_div

../../submodules/PulseRain_MCU/memory/microsemi/dual_port_ram.v
../../submodules/PulseRain_MCU/memory/microsemi/single_port_ram.v
../../submodules/PulseRain_MCU/memory/microsemi/single_port_ram_8bit.v
../../submodules/PulseRain_MCU/memory/sim/SP256K.v
../../submodules/PulseRain_MCU/memory/sim/single_port_ram_sim.v
../../submodules/PulseRain_MCU/peripherals/UART/UART_TX.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_controller.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_CSR.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_data_access.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/mul_div/long_slow_div_denom_reg.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/mul_div/mul_div_32.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/mul_div/absolute_value.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_fetch_instruction.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_execution_unit.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_memory.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_instruction_decode.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/PulseRain_RV2T_core.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_machine_timer.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_reg_file.v
../../submodules/PulseRain_MCU/PulseRain_processor_core/source/RV2T_mm_reg.v

../../submodules/PulseRain_MCU/source/PulseRain_RV2T_MCU.v
../iverilog/mcu_tb.v
